CREATE TABLE Author(
    id BIGINT generated by default as identity (start with 1),
    name VARCHAR(60) NOT NULL,
    biography VARCHAR(255),
    twitter VARCHAR(255),
    website VARCHAR(255),
    source_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE Manga(
    id BIGINT generated by default as identity (start with 1),
    source_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    original_language VARCHAR(30),
    status VARCHAR(20),
    is_locked BOOLEAN NOT NULL,
    year INTEGER,
    description VARCHAR(255),
    author_id BIGINT,
    PRIMARY KEY (id),
);
CREATE TABLE Genre(
    id BIGINT generated by default as identity (start with 1),
    name VARCHAR(255) NOT NULL,
    source_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE Manga_Genre(
    manga_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (manga_id, genre_id),
    FOREIGN KEY (manga_id) REFERENCES Manga(id),
    FOREIGN KEY (genre_id) REFERENCES Genre(id)
);
ALTER TABLE Manga ADD FOREIGN KEY (author_id) REFERENCES Author(id);